# RANDOM WALLETS MODE
RANDOM_WALLET = False  # True or False

SLEEP_FROM = 30  # Second
SLEEP_TO = 100  # Second

# PROXY MODE
USE_PROXY = False

# USE MOBILE PROXY
USE_MOBILE_PROXY = False

# MOBILE PROXY user:pass@host:port
MOBILE_PROXY = ""

# CHANGE PROXY URL
CHANGE_PROXY_URL = ""

# GWEI CONTROL MODE
CHECK_GWEI = True  # True or False
MAX_GWEI = 25

GAS_MULTIPLIER = 1.3

# RETRY MODE
RETRY_COUNT = 1

# DECRYPT ACCOUNTS
DECRYPT_ACCOUNTS = True

# DECRYPT ACCOUNTS PASSWORD
DECRYPT_ACCOUNTS_PASS = "KDvaIc7AQao4f"

# CONTRACTS FOR MINT ON NFTS2ME
NFTS2ME_CONTRACTS = []
